### PR TITLE
#161209990 tests for API 

### PR DESCRIPTION
**Pull request by nesh-dev**
### What does this PR do? 
It has all the tests for the various endpoints for the app includes:
- auth endpoints 
- category endpoints 
- product endpoints 
- sales endpoints 

### Description of Task completed?
Have tests for the API endpoints 

### How to Manually test this?
 
- Clone the repository `git clone https://github.com/kevinene91/Store-Manager-API.git`
- Change into the app directory `cd Store-Manager-API`
- get this branch code `git fetch origin ch-tests-161209990`
- Navigate the folder structure
- create a virtual environment `python3 -m pyvenv venv`
- pip install -r requirements.txt
-  run `pytest` 47 tests should fail 

### Relevant PVT story? 

[161209990](https://www.pivotaltracker.com/n/projects/2203367/stories/161209990)

### CODE REVIEW

**Comment by r-wambui** [comment]
I have cloned the product, but I can only see 4 tests when I run `pytest`. However the 4 have errors. Also ensure you adhere to the PEP 8 guidelines

**Comment by r-wambui** [comment]
Make use other types of `assert` e.g `assertEqual ` assertTrue`.

**Comment by r-wambui** [comment]
Use python unittest for the TDD instead of pytest.
https://docs.python.org/2/library/unittest.html

**Comment by r-wambui** [comment]
Add the travis badge to the readme

**Comment by nesh-dev** [comment]
> Use python unittest for the TDD instead of pytest.
> https://docs.python.org/2/library/unittest.html
The instructions have asked us to use pytest

**Comment by nesh-dev** [comment]
> I have clone the product, but I can only see for tests when I run `pytest`. However the 4 have errors. Also ensure you adhere to the PEP 8 guidelines

please color on this

**Pull request merged**
